# GitHub Actions Workflow for PramodChandrayan/neurochatagent
# Deploy Streamlit Finance Chatbot to Google Cloud Run using Workload Identity Federation

name: Deploy Finance Chatbot to Cloud Run

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual trigger

env:
  GCP_PROJECT_ID: neurofinance-468916
  REGION: us-central1
  SERVICE_NAME: finance-chatbot

permissions:
  id-token: write  # Required for WIF OIDC
  contents: read    # Required for repo checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: projects/71586032565/locations/global/workloadIdentityPools/github-actions-pool-1755718543/providers/github-actions-provider
        service_account: gha-deployer@neurofinance-468916.iam.gserviceaccount.com
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      
    - name: Configure Docker
      run: gcloud auth configure-docker
      
    - name: Build and push container
      run: |
        docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        image: gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        region: ${{ env.REGION }}
        env_vars: |
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT=${{ secrets.PINECONE_ENVIRONMENT }}
          CHUNK_SIZE=${{ secrets.CHUNK_SIZE }}
          CHUNK_OVERLAP=${{ secrets.CHUNK_OVERLAP }}
        port: 8501
        cpu: 1
        memory: 2Gi
        max_instances: 10
        concurrency: 80
        timeout: 300
        
    - name: Show service URL
      run: |
        echo "🎉 Finance Chatbot deployed successfully!"
        echo "🌐 Service URL: $(gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --format='value(status.url)')"
        echo "📊 Service Info:"
        gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --format="table(metadata.name,status.url,spec.template.spec.containers[0].image,spec.template.spec.containers[0].resources.limits.cpu,spec.template.spec.containers[0].resources.limits.memory)"
